title: "Haonan Wang's Homepage"
url: "https://hixuia.github.io"
author: "Haonan Wang"

markdown: kramdown

tracking_id: #

footer: yes
template_url: "https://github.com/ankitsultana/researcher/tree/gh-pages"
template_name: "template designed by Ankit Sultana"
footer_text: ""
last_modified_at: "March-2025"
github: "https://github.com/hiuxia"

sass:
    style: expanded 
    sass_dir: _sass

nav:
#  - name: "About"
#    link: ""
#  - name: "CV"
#    link: "resume.pdf"
